api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'), # localhost:8000/api/
    path('server_info/', views.index, name='server_info'),
    path('api_home/', views.api_home, name='api_home'), # localhost:8000/api/
    path('product_home_raw/', views.product_home_raw, name='product_home_raw'),
    # path('', views.index, name='index'),
    # path('', views.index, name='index'),



    # path('auth/', obtain_auth_token),
    # path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    # # path('products/', include('products.urls'))
]

django-ulti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),

    path("", include("core.urls")),
    path('blog/', include('blog.urls')),
    path('social/', include('social.urls')),
    path('todo/', include('todo.urls')),
    path('music/', include('music.urls')),
    path('radio/', include('radio.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

handler404 = 'django-ulti.views.custom_error_404'
handler500 = 'django-ulti.views.custom_error_500'
handler403 = 'django-ulti.views.custom_error_403'

homeserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),

    path("", include("core.urls")),
    path('blog/', include('blog.urls')),
    path('social/', include('social.urls')),
    path('todo/', include('todo.urls')),
    path('music/', include('music.urls')),
    path('radio/', include('radio.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

handler404 = 'homeserver.views.custom_error_404'
handler500 = 'homeserver.views.custom_error_500'
handler403 = 'homeserver.views.custom_error_403'

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/favorite/', views.favorite, name='favorite'),
    # path('events/<int:pk>/', event_gallery_view, name="event_gallery"),
]

social/urls.py
from django.urls import path

from . import views


app_name = 'social'

urlpatterns = [
    # path("", index.as_view(), name="home"),
    path('', views.index, name='index'),
    path('settings/', views.settings, name='settings'),
    path('upload', views.upload, name='upload'),
    path('follow', views.follow, name='follow'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('like-post/', views.like_post, name='like-post'),
    path('logout/', views.logout, name='logout'),
    # path('signin/', views.signin, name='signin'),


    path('search/', views.search, name='search'),
    # path('signup/', views.signup, name='signup'),
]

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return '[{} - {}]'.format(self.artist, self.album_title)

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return '[{} - {}] {} / {}'.format(self.album.artist, self.album.album_title, self.song_title, self.file_type)

music/views.py
from django.http import Http404
# from django.http import HttpResponse
# from django.template import loader
from django.shortcuts import render, get_object_or_404
# from django.views.generic import TemplateView
from .models import Album

# Create your views here.
def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums': all_albums,}
    return render(request, 'music/index.html', context)


def detail(request, pk):
    album = get_object_or_404(Album, pk=pk)
    context = {'album': album,}

    return render(request, 'music/detail.html', context)

def favorite(request, pk):
    album = get_object_or_404(Album, pk=pk)
    context = {'album': album}

    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        context['error_msg'] = "No song selected!!"
        return render(request, 'music/detail.html', context)
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', context)

# def <modelname>(request, pk):
    # template = loader.get_template('music/index.html')
    # return HttpResponse(template.render(context, request))

    # try:
    #     album = Album.objects.get(pk=pk)
    #     context = {
    #             'album': album,
    #     }
    # except Album.DoesNotExist:
    #     raise Http404('Album does not exist!!')
    # return render(request, 'music/detail.html', context)

    # return HttpResponse("<h1> Music  - Details for album ID : {}</h1>".format(pk))

music/templates/music/detail.html
{% extends 'middle.html' %}
{% load static %}

{% block title %}Album Detail{% endblock %}

{% block middlecontent %}

{% if error_msg %}
<p><strong>{{ error_msg }}</strong></p>
{% endif %}

<h1>{{ album }}</h1>
ALBUM_LOGO:<img src="{{ album.album_logo }}"/>
<h2>ALBUM_TITLE:{{ album.album_title }}</h2>
<h3>ARTIST:{{ album.artist }}</h3>
<h4>GENRE:{{ album.genre }}</h4>

<hr>
<h2>Song List:</h2>
<hr>

<ul>
{% if album.song_set.all %}
  {% for song in album.song_set.all %}
  <li>{{song.song_title}} - {{song.file_type}}</li>
  {% endfor %}
{% else %}
  <li>No songs Found!!</li>
{% endif %}
</ul>


<form action="{% url 'music:favorite' album.id %}" method="post">
  {% csrf_token %}
  {% if album.song_set.all %}
    {% for song in album.song_set.all %}
    <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
    <label for="song{{ forloop.counter }}">
      {{song.song_title}} - {{song.file_type}}
      {% if song.is_favorite %}
        <img src="https://mario.wiki.gallery/images/thumb/8/8a/New_Super_Mario_Bros._U_Deluxe_Super_Star.png/200px-New_Super_Mario_Bros._U_Deluxe_Super_Star.png"/>
      {% else %}
        <img src="#"/>
      {% endif %}
    </label><br>
    {% endfor %}
    <input type="submit" value="favorite">
  {% else %}
    <h4>No songs Found!!</h4>
  {% endif %}
</form>

https://mario.wiki.gallery/images/thumb/8/8a/New_Super_Mario_Bros._U_Deluxe_Super_Star.png/200px-New_Super_Mario_Bros._U_Deluxe_Super_Star.png
{% endblock middlecontent %}

music/templates/music/index.html
{% extends 'middle.html' %}
{% load static %}

{% block title %}Album List{% endblock %}

{% block mainnavmediaactive %}active{% endblock mainnavmediaactive %}

{% block breadcrumb %}
<!-- Breadcrumb -->
<div class="container-fluid px-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'social:index' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">TEMP TEMP <b>{{user.username}}</b></li>
    </ol>
  </nav>
</div>

{% endblock breadcrumb %}

{% block middlecontent %}

<h1>Album List</h1>
<ul>
{% if all_albums %}
  {% for album in all_albums %}
  <li><a href="{% url 'music:detail' album.id %}"> {{album.album_title}} </a></li>
  {% endfor %}
{% else %}
  <li>No Albums Found!!</li>
{% endif %}
</ul>

<div class="row">
  <div class="col">

    <div class="card shadow-sm">
      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

      <div class="card-body">
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
          </div>
          <small class="text-muted">9 mins</small>
        </div>
      </div>
    </div>
  </div>
</div>

Blog Idea: https://getbootstrap.com/docs/5.0/examples/blog/
----------------
Login Idea: https://getbootstrap.com/docs/5.0/examples/sign-in/
----------------
https://github.com/wsvincent/djangox/tree/master/templates/account
----------------
https://django-allauth.readthedocs.io/en/latest/configuration.html
{% endblock middlecontent %}