api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'), # localhost:8000/api/
    path('server_info/', views.index, name='server_info'),
    path('api_home/', views.api_home, name='api_home'), # localhost:8000/api/
    path('product_home_raw/', views.product_home_raw, name='product_home_raw'),
    # path('', views.index, name='index'),
    # path('', views.index, name='index'),



    # path('auth/', obtain_auth_token),
    # path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    # # path('products/', include('products.urls'))
]

django-ulti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),

    path("", include("core.urls")),
    path('blog/', include('blog.urls')),
    path('social/', include('social.urls')),
    path('todo/', include('todo.urls')),
    path('music/', include('music.urls')),
    path('radio/', include('radio.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

handler404 = 'django-ulti.views.custom_error_404'
handler500 = 'django-ulti.views.custom_error_500'
handler403 = 'django-ulti.views.custom_error_403'

homeserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),

    path("", include("core.urls")),
    path('blog/', include('blog.urls')),
    path('social/', include('social.urls')),
    path('todo/', include('todo.urls')),
    path('music/', include('music.urls')),
    path('radio/', include('radio.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

handler404 = 'homeserver.views.custom_error_404'
handler500 = 'homeserver.views.custom_error_500'
handler403 = 'homeserver.views.custom_error_403'

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='home'),
    path('create/', views.create_todo, name='create-todo'),
    path('todo/<id>/', views.todo_detail, name='todo'),
    path('todo-delete/<id>/', views.todo_delete, name='todo-delete'),
    path('edit-todo/<id>/', views.todo_edit, name='todo-edit'),
    path('todo-orderby/<col_pri_str>/<asc_dsc>/', views.order_by, name='todo-orderby',),
    path('todo-orderby/<col_pri_str>/', views.order_by, name='todo-orderby',),
    path('todo-filterview/<filter>/', views.complete_filter_view, name='todo-filterview',),
]

todo/models.py
from django.db import models
from core.models import User, TrackingModel
# Create your models here.


class Control(TrackingModel):

    class order_by(models.TextChoices):
        TITLE = 'TITLE'
        DESCRIPTION = 'DESCRIPTION'
        COMPLETE = 'COMPLETE'

    class complete_filters(models.TextChoices):
        NO = 'NO'
        YES = 'YES'
        ALL = 'ALL'

    title_order = models.BooleanField(default=True, null=False)
    description_order = models.BooleanField(default=True, null=False)
    complete_order = models.BooleanField(default=True, null=False)
    col_pri = models.CharField(max_length=255, choices=order_by.choices, default=order_by.TITLE)
    complete_filter = models.CharField(max_length=255, choices=complete_filters.choices, default=complete_filters.ALL)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return "{},{},{},{}".format(self.title_order, self.description_order, self.complete_order, self.col_pri)

    def get_title_order(self):
        if self.title_order == True:
            return 'asc'
        elif self.title_order == False:
            return 'dsc'
        else:
            return "Error"

    def get_description_order(self):
        if self.description_order == True:
            return 'asc'
        elif self.description_order == False:
            return 'dsc'
        else:
            return "Error"

    def get_complete_order(self):
        if self.complete_order == True:
            return 'asc'
        elif self.complete_order == False:
            return 'dsc'
        else:
            return "Error"


class Todo(TrackingModel):

    title = models.CharField(max_length=255)
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo

        fields = ['title', 'description', 'is_completed']

todo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import TodoForm
from .models import Todo, Control
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.
class HomePageView(TemplateView):
    template_name = "todo/home.html"

@login_required
def get_showing_todos(request, todos, controls):
    if controls.title_order == True:
        title_order_val = 'title'
    else:
        title_order_val = '-title'
    if controls.description_order == True:
        description_order_val = 'description'
    else:
        description_order_val = '-description'
    if controls.complete_order == True:
        is_completed_order_val = 'is_completed'
    else:
        is_completed_order_val = '-is_completed'


    if controls.col_pri == Control.order_by.TITLE:
        print("TITLE order")
        pri_col = title_order_val
        sec_col = description_order_val
        tri_col = is_completed_order_val
    if controls.col_pri == Control.order_by.DESCRIPTION:
        print("DESCRIPTION order")
        pri_col = description_order_val
        sec_col = title_order_val
        tri_col = is_completed_order_val
    if controls.col_pri == Control.order_by.COMPLETE:
        print("COMPLETE order")
        pri_col = is_completed_order_val
        sec_col = title_order_val
        tri_col = description_order_val

    if controls.complete_filter == Control.complete_filters.YES:
        return todos.filter(is_completed=True).order_by(pri_col, sec_col, tri_col)
    if controls.complete_filter == Control.complete_filters.NO:
        return todos.filter(is_completed=False).order_by(pri_col, sec_col, tri_col)
    if controls.complete_filter == Control.complete_filters.ALL:
        return todos.order_by(pri_col, sec_col, tri_col)

@login_required
def index(request):
    todos = Todo.objects.filter(owner=request.user)
    controls = Control.objects.filter(user=request.user)
    if controls.exists():
        controls = controls[0]
    else:
        controls = Control.objects.create(user=request.user)
        return HttpResponseRedirect(reverse('todo:home'))

    completed_count = todos.filter(is_completed=True).count()
    incomplete_count = todos.filter(is_completed=False).count()
    all_count = todos.count()

    context = {'controls':controls, 'todos': get_showing_todos(request, todos, controls), 'all_count': all_count,
               'completed_count': completed_count, 'incomplete_count': incomplete_count}
    return render(request, 'todo/index.html', context)

@login_required
def order_by(request, col_pri_str, asc_dsc=None):
    controls = Control.objects.filter(user=request.user).first()

    if (asc_dsc is not None) and (asc_dsc == 'True'):
        asc_dsc = True
    elif (asc_dsc is not None) and (asc_dsc == 'False'):
        asc_dsc = False

    if col_pri_str == Control.order_by.TITLE:
        controls.col_pri = Control.order_by.TITLE
        if (asc_dsc is None):
            controls.title_order = not controls.title_order
        else:
            controls.title_order = asc_dsc
        # messages.add_message(request, messages.SUCCESS, "Order By {} {}".format(Control.order_by.TITLE, asc_dsc))
    elif col_pri_str == Control.order_by.DESCRIPTION:
        controls.col_pri = Control.order_by.DESCRIPTION
        if (asc_dsc is None):
            controls.description_order = not controls.description_order
        else:
            controls.description_order = asc_dsc
        # messages.add_message(request, messages.SUCCESS, "Order By {} {}".format(Control.order_by.DESCRIPTION, asc_dsc))
    elif col_pri_str == Control.order_by.COMPLETE:
        controls.col_pri = Control.order_by.COMPLETE
        if (asc_dsc is None):
            controls.complete_order = not controls.complete_order
        else:
            controls.complete_order = asc_dsc
        # messages.add_message(request, messages.SUCCESS, "Order By {} {}".format(Control.order_by.COMPLETE, asc_dsc))

    if controls.user == request.user:
        controls.save()
    return HttpResponseRedirect(reverse('todo:home'))

@login_required
def complete_filter_view(request, filter):
    controls = Control.objects.filter(user=request.user).first()
    if filter == Control.complete_filters.ALL:
        controls.complete_filter = Control.complete_filters.ALL
    elif filter == Control.complete_filters.NO:
        controls.complete_filter = Control.complete_filters.NO
    elif filter == Control.complete_filters.YES:
        controls.complete_filter = Control.complete_filters.YES
    # messages.add_message(request, messages.SUCCESS, "COMPLETE - {}".format(controls.complete_filter))

    if controls.user == request.user:
        # print(controls.title_order)
        # print(controls.description_order)
        # print(controls.complete_order)
        # print(controls.col_pri)
        # print(controls.complete_filter)

        controls.save()
    return HttpResponseRedirect(reverse('todo:home'))

@login_required
def create_todo(request):
    form = TodoForm()
    context = {'form': form}

    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        is_completed = request.POST.get('is_completed', False)

        todo = Todo()

        todo.title = title
        todo.description = description
        todo.is_completed = True if is_completed == "on" else False
        todo.owner = request.user
        todo.save()

        messages.add_message(request, messages.SUCCESS, "Todo created successfully")

        return HttpResponseRedirect(reverse("todo:todo", kwargs={'id': todo.pk}))

    return render(request, 'todo/create-todo.html', context)

@login_required
def todo_detail(request, id):
    todo = get_object_or_404(Todo, pk=id)
    context = {'todo': todo}
    return render(request, 'todo/todo-detail.html', context)

@login_required
def todo_delete(request, id):
    todo = get_object_or_404(Todo, pk=id)
    context = {'todo': todo}

    if request.method == 'POST':
        if todo.owner == request.user:
            todo.delete()
            messages.add_message(request, messages.SUCCESS, "Todo deleted successfully"
                                 )
            return HttpResponseRedirect(reverse('todo:home'))
        return render(request, 'todo/todo-delete.html', context)

    return render(request, 'todo/todo-delete.html', context)

@login_required
def todo_edit(request, id):
    todo = get_object_or_404(Todo, pk=id)
    form = TodoForm(instance=todo)
    context = {'todo': todo, 'form': form}

    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        is_completed = request.POST.get('is_completed', False)

        todo.title = title
        todo.description = description
        todo.is_completed = True if is_completed == "on" else False

        if todo.owner == request.user:
            todo.save()

        messages.add_message(request, messages.SUCCESS, "Todo update success"

                             )

        return HttpResponseRedirect(reverse("todo:todo", kwargs={'id': todo.pk}))

    return render(request, 'todo/todo-edit.html', context)

todo/templates/todo/create-todo.html
{% extends "card.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}

{% load i18n %}

{% block title %}Create Todo{% endblock title %}
{% block mainnavtodoactive %}active{% endblock mainnavtodoactive %}
{% block cardheadercontent %}Create Todo{% endblock cardheadercontent %}

{% block breadcrumb %}
<!-- Breadcrumb -->
<div class="container-fluid px-5">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'todo:home' %}">Home</a></li>
		<li class="breadcrumb-item active" aria-current="page">{{user.username}}!? Add a To-Do?</b></li>
	</ol>
</nav>
</div>

{% endblock breadcrumb %}

{% block cardbodycontent %}
<form method="POST" action={% url 'todo:create-todo'  %}>
        {% csrf_token %}

        {{form|crispy}}
{% endblock cardbodycontent %}


{% block cardfootercontent %}
<input type="submit" class="ui button primary" value="Submit">
</form>
{% endblock cardfootercontent %}

todo/templates/todo/home.html
{% extends 'middle.html' %}

{% block title %}Todo-Home{% endblock %}

{% block mainnavtodoactive %}active{% endblock mainnavtodoactive %}
{% block submenu %}
  <a class="nav-link active mx-1" aria-current="page" href="#" role="button">blog - default</a>
  <a class="nav-link active mx-1" href="#">Todo - default</a>
{% endblock submenu %}

{% block middlecontent %}
<h1>Todo-Home</h1>
{% endblock middlecontent %}

todo/templates/todo/index.html
{% extends 'middle.html' %}
{% block title %}
My List of Todos
{% endblock %}
{% load static %}


{% block mainnavtodoactive %}active{% endblock mainnavtodoactive %}

{% block breadcrumb %}
<!-- Breadcrumb -->
<div class="container-fluid px-5">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'todo:home' %}">Home</a></li>
		<li class="breadcrumb-item active" aria-current="page">{{user.username}}'s To-Do List</b></li>
	</ol>
</nav>
</div>

{% endblock breadcrumb %}


{% block middlecontent %}

<div class="row justify-content-center">
	<div class="col-12 py-3">

		<div class="card">
			{% if todos %}
			<div class="card-header">
				My List of Todos
			</div>
			<div class="card-body">
				<table class="table table-light table-striped">
					<thead>
						<tr>
							<th scope="col">
								<div class="btn-group">
									<a href="{% url 'todo:todo-orderby' 'TITLE' %}" role="button" class="btn btn-primary">
										Title
									</a>
									<button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
										<span class="visually-hidden">Toggle Dropdown</span>
									</button>
									<ul class="dropdown-menu">
										<li>
											<p class="px-2">Order by:</P>
										</li>
										<li><a class="dropdown-item" href="{% url 'todo:todo-orderby' 'TITLE' True %}">A->Z</a></li>
										<li><a class="dropdown-item" href="{% url 'todo:todo-orderby' 'TITLE' False %}">Z->A</a></li>
									</ul>
								</div>

							</th>
							<th scope="col">
								<div class="btn-group">
									<a href="{% url 'todo:todo-orderby' 'DESCRIPTION' %}" role="button" class="btn btn-primary">
										Description
									</a>
									<button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
										<span class="visually-hidden">Toggle Dropdown</span>
									</button>
									<ul class="dropdown-menu">
										<li>
											<p class="px-2">Order by:</P>
										</li>
										<li><a class="dropdown-item" href="{% url 'todo:todo-orderby' 'DESCRIPTION' True %}">A->Z</a></li>
										<li><a class="dropdown-item" href="{% url 'todo:todo-orderby' 'DESCRIPTION' False %}">Z->A</a></li>
									</ul>
								</div>
							</th>
							<th scope="col">
								<div class="btn-group">
									<a href="{% url 'todo:todo-orderby' 'COMPLETE' %}" role="button" class="btn btn-primary">
										Completed
									</a>
									<button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
										<span class="visually-hidden">Toggle Dropdown</span>
									</button>
									<ul class="dropdown-menu">
										<li>
											<p class="px-2">Order by:</P>
										</li>
										<li><a class="dropdown-item" href="{% url 'todo:todo-orderby' 'COMPLETE' True %}">No->Yes</a></li>
										<li><a class="dropdown-item" href="{% url 'todo:todo-orderby' 'COMPLETE' False %}">Yes->No</a></li>
										<li><hr class="dropdown-divider"></li>
										<li>
											<p class="px-2">Filter by:</P>
										</li>
										<li>
											<a href="{% url 'todo:todo-filterview' 'ALL' %}" class="dropdown-item" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
											All {{all_count}}</a>
										</li>
										<li>
											<a href="{% url 'todo:todo-filterview' 'YES' %}" class="dropdown-item" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
												Completed <span class="badge rounded-pill bg-success">{{completed_count}}</span>
											</a>
										</li>
										<li>
											<a href="{% url 'todo:todo-filterview' 'NO' %}" class="dropdown-item" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
												Remaining <span class="badge rounded-pill bg-primary">{{incomplete_count}}</span>
											</a>
										</li>
									</ul>
								</div>

							</th>
							<th scope="col">Actions</th>
						</tr>
					</thead>
					<tbody class="table-group-divider">
						{% for todo in todos %}
						<tr>
							<th scope="row">
								<a href='{% url 'todo:todo' todo.pk %}'>
								{{todo.title}}
								</a>
								</th>
								<td>{{todo.description}}</td>
								<td>
								{% if todo.is_completed %}
								YES <i class="check icon green"></i>
								{% else %}
								NO
								{% endif %}
								</td>
								<td>
								<a href={% url 'todo:todo' todo.pk  %} class="btn btn-primary mx-2" role="button">
									<i class="bi bi-eye-fill"></i> View
								</a>
								<a href={% url 'todo:todo-edit' todo.pk  %} class="btn btn-primary mx-2" role="button">
									<i class="bi bi-pen-fill"></i> Edit
								</a>
								<a href={% url 'todo:todo-delete' todo.pk  %} class="btn btn-danger mx-2" role="button">
									<i class="bi bi-trash-fill"></i> Delete
								</a>
							</td>
						</tr>
						{% endfor %}
					</tbody>

				</table>
			</div>
			<div class="card-footer">
				<div class="container">
					<div class="row">
						<div class="col-3">
							<a class="btn btn-success" href="{% url 'todo:create-todo' %}" role="button">
							Add new</a>
						</div>
						<div class="col-9 d-flex justify-content-end">
							<a href="{% url 'todo:todo-filterview' 'ALL' %}" role="button" class="btn btn-primary mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
								All <span class="badge bg-secondary">{{all_count}}</span>
							</a>

							<a href="{% url 'todo:todo-filterview' 'NO' %}" role="button" class="btn btn-primary mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
								Remaining <span class="badge bg-secondary">{{incomplete_count}}</span>
							</a>

							<a href="{% url 'todo:todo-filterview' 'YES' %}" role="button" class="btn btn-primary mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
								Completed <span class="badge bg-secondary">{{completed_count}}</span>
							</a>
						</div>
					</div>
				</div>



			</div>
			{% else %}
			<div class="card-header">
				My List of Todos
			</div>
			<div class="card-body">
				<h5 class="card-title">No items yet</h5>
				<p class="card-text">You can create your first todo now</p>
			</table>
			</div>
			<div class="card-footer">
				<div class="container">
					<div class="row">
						<div class="col-3">
							<a class="btn btn-success" href="{% url 'todo:create-todo' %}" role="button">
							Add new</a>
						</div>
						<div class="col-9 d-flex justify-content-end">
							<a href="{% url 'todo:todo-filterview' 'ALL' %}" role="button" class="btn btn-primary mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
								All <span class="badge bg-secondary">{{all_count}}</span>
							</a>

							<a href="{% url 'todo:todo-filterview' 'NO' %}" role="button" class="btn btn-primary mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
								Remaining <span class="badge bg-secondary">{{incomplete_count}}</span>
							</a>

							<a href="{% url 'todo:todo-filterview' 'YES' %}" role="button" class="btn btn-primary mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on top">
								Completed <span class="badge bg-secondary">{{completed_count}}</span>
							</a>
						</div>
					</div>
				</div>
			</div>
			{% endif %}
	</div>

</div>
</div>
{% endblock middlecontent %}

todo/templates/todo/todo-delete.html
{% extends "card.html" %}
{% load django_bootstrap5 %}

{% load i18n %}

{% block title %}Delete Todo?{% endblock title %}
{% block mainnavtodoactive %}active{% endblock mainnavtodoactive %}
{% block cardheadercontent %}Delete Todo?{% endblock cardheadercontent %}

{% block breadcrumb %}
<!-- Breadcrumb -->
<div class="container-fluid px-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'todo:home' %}">Home</a></li>
		<li class="breadcrumb-item active" aria-current="page">Delete - Task {{todo.id}} by {{user.username}}</b></li>
    </ol>
  </nav>
</div>

{% endblock breadcrumb %}

{% block cardbodycontent %}
<form method="POST"  action={% url 'todo:todo-delete' todo.id %} class="form">
	{% csrf_token %}
	<p class="card-text">Are you sure you want to delete this todo?</p>
	
	
	{% endblock cardbodycontent %}
	
	
	{% block cardfootercontent %}
	<input type="submit" class="btn btn-success" value="YES">
	<a class="btn btn-danger" href={% url 'todo:todo' todo.id %} role="button">Cancel</a>
</form>
{% endblock cardfootercontent %}

todo/templates/todo/todo-detail.html
{% extends "card.html" %}
{% load django_bootstrap5 %}

{% load i18n %}

{% block title %}Todo Detail{% endblock title %}
{% block mainnavtodoactive %}active{% endblock mainnavtodoactive %}
{% block cardheadercontent %}Todo Detail{% endblock cardheadercontent %}


{% block breadcrumb %}
<!-- Breadcrumb -->
<div class="container-fluid px-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'todo:home' %}">Home</a></li>
		<li class="breadcrumb-item active" aria-current="page">Detail - Task {{todo.id}} by {{user.username}}</b></li>
    </ol>
  </nav>
</div>

{% endblock breadcrumb %}



{% block cardbodycontent %}
<h5 class="card-title">{{todo.title}}</h5>
<h6 class="card-subtitle mb-2 text-muted">{{todo.created_at}}</h6>
<p class="card-text">
	{{todo.description}}
</p>

{% endblock cardbodycontent %}



{% block cardlistcontent %}

  <ul class="list-group list-group-flush">
	<li class="list-group-item">
	{% if todo.is_completed%}
		Completed at {{todo.updated_at}}
	{% else %}
		No yet completed
	{% endif %}
	</li>
  </ul>
  <div class="card-header">
    Action List
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Action item</li>
  </ul>
{% endblock cardlistcontent %}

{% block cardfootercontent %}
<a class="btn btn-primary" role="button" href="{% url 'todo:todo-edit' todo.id %}">Edit</a>
<a class="btn btn-danger" role="button" href="{% url 'todo:todo-delete' todo.id %}">Delete this todo</a>
<a class="btn btn-success" role="button" href="{% url 'todo:create-todo' %}">Add new</a>
{% endblock cardfootercontent %}

todo/templates/todo/todo-edit.html
{% extends "card.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}Edit Todo{% endblock title %}
{% block mainnavtodoactive %}active{% endblock mainnavtodoactive %}
{% block cardheadercontent %}Edit Todo{% endblock cardheadercontent %}


{% block breadcrumb %}
<!-- Breadcrumb -->
<div class="container-fluid px-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'todo:home' %}">Home</a></li>
		<li class="breadcrumb-item active" aria-current="page">Edit - Task {{todo.id}} by {{user.username}}</b></li>
    </ol>
  </nav>
</div>

{% endblock breadcrumb %}

{% block cardbodycontent %}
<form class="form" method="POST" action={% url 'todo:todo-edit' todo.id   %}>
	{% csrf_token %}


  {{form|crispy}}


	{% endblock cardbodycontent %}


	{% block cardfootercontent %}
	<input type="submit" class="btn btn-success" value="Save">
  <a class="btn btn-success" role="button" href="{% url 'todo:create-todo' %}">Add new</a>
</form>
{% endblock cardfootercontent %}