api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'), # localhost:8000/api/
    path('server_info/', views.index, name='server_info'),
    path('api_home/', views.api_home, name='api_home'), # localhost:8000/api/
    path('product_home_raw/', views.product_home_raw, name='product_home_raw'),
    # path('', views.index, name='index'),
    # path('', views.index, name='index'),



    # path('auth/', obtain_auth_token),
    # path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    # # path('products/', include('products.urls'))
]

blog/urls.py
from django.urls import path

from .views import HomePageView

app_name = 'blog'

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("about/", views.AboutPageView.as_view(), name="about"),
    path("contact/", views.ContactPageView.as_view(), name="contact"),
    # path('login', views.login_user, name='login'),
    # path('register', views.register, name='register'),
    # path("logout_user", views.logout_user, name='logout_user'),
    # path('activate-user/<uidb64>/<token>',
    #      views.activate_user, name='activate'),
    #path("account/ssignup/", views.AccountSignupView.as_view(), name='account_signup_custom'),
]

django-ulti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),

    path("", include("core.urls")),
    path('blog/', include('blog.urls')),
    path('social/', include('social.urls')),
    path('todo/', include('todo.urls')),
    path('music/', include('music.urls')),
    path('radio/', include('radio.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

handler404 = 'django-ulti.views.custom_error_404'
handler500 = 'django-ulti.views.custom_error_500'
handler403 = 'django-ulti.views.custom_error_403'

homeserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),

    path("", include("core.urls")),
    path('blog/', include('blog.urls')),
    path('social/', include('social.urls')),
    path('todo/', include('todo.urls')),
    path('music/', include('music.urls')),
    path('radio/', include('radio.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

handler404 = 'homeserver.views.custom_error_404'
handler500 = 'homeserver.views.custom_error_500'
handler403 = 'homeserver.views.custom_error_403'

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/favorite/', views.favorite, name='favorite'),
    # path('events/<int:pk>/', event_gallery_view, name="event_gallery"),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='home'),
    path('create/', views.create_todo, name='create-todo'),
    path('todo/<id>/', views.todo_detail, name='todo'),
    path('todo-delete/<id>/', views.todo_delete, name='todo-delete'),
    path('edit-todo/<id>/', views.todo_edit, name='todo-edit'),
    path('todo-orderby/<col_pri_str>/<asc_dsc>/', views.order_by, name='todo-orderby',),
    path('todo-orderby/<col_pri_str>/', views.order_by, name='todo-orderby',),
    path('todo-filterview/<filter>/', views.complete_filter_view, name='todo-filterview',),
]

templates/_base.html
{% extends '_header.html' %}

{% block headercontent %}
<!-- Fixed navbar -->
{% load account %}
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md fixed-top bg-light text-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggleExternalContent">

      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link {% block mainnavhomeactive %}{% endblock mainnavhomeactive %}" aria-current="page" href="{% url 'core:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block mainnavblogactive %}{% endblock mainnavblogactive %}" href="{% url 'blog:home' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block mainnavsocialactive %}{% endblock mainnavsocialactive %}" href="{% url 'social:index' %}">Social</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block mainnavforumactive %}{% endblock mainnavforumactive %}" href="#">Forum</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block mainnavwikiactive %}{% endblock mainnavwikiactive %}" href="#">Wiki</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block mainnavtodoactive %}{% endblock mainnavtodoactive %}" href="{% url 'todo:home' %}">To-Do</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% block mainnavbizactive %}{% endblock mainnavbizactive %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            BizTools
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Tool 1</a></li>
            <li><a class="dropdown-item" href="#">Tool 2</a></li>
            <li><a class="dropdown-item" href="#">Tool 3</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Tool 4</a></li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link {% block mainnavetfmindactive %}{% endblock mainnavetfmindactive %}" href="#">ETF Mind</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% block mainnavfintoolsactive %}{% endblock mainnavfintoolsactive %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            FinTools
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Tool 1</a></li>
            <li><a class="dropdown-item" href="#">Tool 2</a></li>
            <li><a class="dropdown-item" href="#">Tool 3</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Tool 4</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% block mainnavmediaactive %}{% endblock mainnavmediaactive %}" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Media/Radio Tools
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'music:index' %}">Music Player</a></li>
            <li><a class="dropdown-item" href="{% url 'radio:index' %}">Radio</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Tool 2</a></li>
            <li><a class="dropdown-item" href="#">Tool 3</a></li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link {% block mainnavaboutactive %}{% endblock mainnavaboutactive %}" href="{% url 'core:about' %}">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block mainnavcontactactive %}{% endblock mainnavcontactactive %}" href="{% url 'core:contact' %}">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block mainnavsitemapactive %}{% endblock mainnavsitemapactive %}" href="#">Site Map</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block mainnavadminactive %}{% endblock mainnavadminactive %}" href="{% url "admin:index" %}">Admin Site</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% block mainnavaccountactive %}{% endblock mainnavaccountactive %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hi {% user_display user %}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'account_email' %}">Change E-mail</a></li>
            <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change Password</a></li>
            <li><a class="dropdown-item" href="{% url 'account_set_password' %}">Set Password</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign Out</a></li>
            <li><hr class="dropdown-divider"></li>
            {% comment %}<!-- <li><a class="dropdown-item" href="{% url 'account_confirm_email' %}">Email Confirm</a></li> -->{% endcomment %}
            <li><a class="dropdown-item" href="{% url 'account_reset_password' %}">Reset Password</a></li>
            <li><a class="dropdown-item" href="{% url 'account_reset_password_done' %}">Reset Password DONE</a></li>
            {% comment %}<!-- <li><a class="dropdown-item" href="{% url 'account_reset_password_from_key' %}">Reset Password FromKey</a></li> -->{% endcomment %}
            <li><a class="dropdown-item" href="{% url 'account_reset_password_from_key_done' %}">Reset Password FromKey Done</a></li>
            <li><a class="dropdown-item" href="{% url 'account_inactive' %}">Inactive</a></li>
            <li><a class="dropdown-item" href="{% url 'account_email_verification_sent' %}">verification Sent</a></li>
          </ul>
        </li>inactive
        {% else %}
        <li class="nav-item">
          <button type="button" class="btn btn-outline-success me-2"><a href="{% url 'account_login' %}">Log In</a></button>
        </li>
        <li class="nav-item">
          <button type="button" class="btn btn-outline-warning me-2"><a href="{% url 'account_signup' %}">Sign-up</a></button>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<!-- SubMenu -->
<div class="row border-bottom border-top py-1" style="margin-top: 3.5rem !important;">
  <div class="col-md-3">
    <form class="d-flex mb-0 ms-2" role="search">
      <input class="form-control me-2" type="search" placeholder="Search..." aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
  <div class="col col-md-9">
    <nav class="nav nav-pills">
    {% block submenu %}
    {% endblock submenu %}
    </nav>
  </div>

</div>


{% block breadcrumb %}

{% endblock breadcrumb %}



<main class="pb-3">
  <!-- Content -->
  {% block content %}
  <p>Default content...</p>
  {% endblock content %}
</main>

<!-- Footer -->
{# include footer #}
{% include "_footer.html" %}


{% endblock headercontent %}

templates/_footer.html
<!-- <div class='container-fluid'> -->
<footer class="footer mt-auto mx-0 mt-3 px-5 py-1 d-flex justify-content-between align-items-center border-top bg-light text-dark">
    <p class="col-md-4 mb-0">© 2022 Company, Inc</p>

    <a href="/" class="col-md-4 p-0 m-0 mb-md-0 me-md-auto d-flex align-items-center justify-content-center link-light text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-dark">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-dark">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-dark">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-dark">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-dark">About</a></li>
    </ul>
  </footer>
  <!-- </div> -->

templates/_header.html
{% load static %}

<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{% block title %}Site Name{% endblock title %}</title>
  <meta name="description" content="A Django framework.">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

  {% block css %}

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
  <link href="{% static 'css/custom.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  {% endblock css %}

  {% block style %}
  {% endblock style %}

</head>

<body class="d-flex flex-column h-100">
  <!-- Header Content -->
  {% block headercontent %}
    <p>Default [HEADER] content...</p>
  {% endblock headercontent %}


  {% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js" integrity="sha512-6UofPqm0QupIL0kzS/UIzekR73/luZdC6i/kXDbWnLOJoqwklBK6519iUnShaYceJ0y4FaiPtX/hRnV/X/xlUQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

  <!-- Scripts-->
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script> -->
  <!-- <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script> -->
  <!-- <script src="{% static 'js/materialize.js' %}"></script> -->
  <!-- <script src="{% static 'js/base.js' %}"></script> -->
	<script>
		window.onload = (event) => {
		let myAlert = document.querySelectorAll('.toast')[0];
		let bsAlert = new bootstrap.Toast(myAlert);
		bsAlert.show();
	}
	</script>
	<script>
		var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
		var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
		  return new bootstrap.Tooltip(tooltipTriggerEl)
		})
	</script>
  {% endblock javascript %}

  <!-- MessageCenter -->
  {% block message_center %}
    <!-- alerts -->
	<div aria-live="polite" aria-atomic="true" class="bg-dark position-static">
		<div class="toast-container px-4 py-5 top-0 end-0">
			<!--
			<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="5000">
				<div class="toast-header">
					<img src="..." class="rounded me-2" alt="...">
					<strong class="me-auto">Bootstrap</strong>
					<small class="text-muted">just now</small>
					<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
				</div>
				<div class="toast-body">
					This one will disapear
				</div>
			</div>

			<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="false">
				<div class="toast-header">
					<img src="..." class="rounded me-2" alt="...">
					<strong class="me-auto">Bootstrap</strong>
					<small class="text-muted">2 seconds ago</small>
					<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
				</div>
				<div class="toast-body">
					This one will stay open till close
				</div>
			</div>
			-->


			{% if messages %}
				{% for message in messages %}
				<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="3000"> <!-- data-bs-autohide="false" -->
					<div class="toast-header">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-exclamation-fill text-danger" viewBox="0 0 16 16">
              <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 4.697v4.974A4.491 4.491 0 0 0 12.5 8a4.49 4.49 0 0 0-1.965.45l-.338-.207L16 4.697Z"/>
              <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1.5a.5.5 0 0 1-1 0V11a.5.5 0 0 1 1 0Zm0 3a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"/>
            </svg>
						<strong class="me-auto px-2">Message</strong>
						<small class="text-muted">{{message.tags}}</small>
						<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
					</div>
					<div class="toast-body">
						{{message}}
					</div>
				</div>
				{% endfor %}
			{% endif %}
		</div>
	</div>



  {% endblock message_center %}

  {% block javascript_custom %}

  {% endblock javascript_custom %}

  {# block to easily inject any javascript content #}
  {% block extra_scripts %}
  {% endblock %}

</body>

</html>

templates/_radiobase.html
{% extends '_header.html' %}

{% block headercontent %}
  <!-- Menu NONE -->

  <!-- Content -->

  {% block content %}
    <p>Default content...</p>
  {% endblock content %}

  <!-- Footer NONE -->
{% endblock headercontent %}

templates/card.html
{% extends 'middle.html' %}
{% load static %}


{% block style %}
{% endblock style %}



{% block submenu %}
{% endblock submenu %}

{% block breadcrumb %}
{% endblock breadcrumb %}

{% block middlecontent %}
<div class="row justify-content-center">
	<div class="col-md-6 py-3">
		<div class="card">
			{% block customcardcontent %}
			<div class="card-header">
				{% block cardheadercontent %}
				Card Title
				{% endblock cardheadercontent %}
			</div>
			<div class="card-body">
				{% block cardbodycontent %}
				This is some text within a card body.
				{% endblock cardbodycontent %}
			</div>
			{% block cardlistcontent %}
			{% endblock cardlistcontent %}
			<div class="card-footer">
				{% block cardfootercontent %}
				Card footer
				{% endblock cardfootercontent %}
			</div>
			{% endblock customcardcontent %}
		</div>
	</div>
</div>
{% endblock middlecontent %}

{% block javascript_custom %}
{% endblock javascript_custom %}

templates/main_full.html
{% extends '_base.html' %}

{% block content %}
  <!-- Menu NONE -->

  <!-- mainfull Content -->
  <div class="container-fluid">
  {% block mainfullcontent %}
    <div class="row">
      <div class="col-md-2">{% block main_l_content %}main_l_content{% endblock main_l_content %}</div>
      <div class="col-md-8">{% block main_mid_content %}main_mid_content{% endblock main_mid_content %}</div>
      <div class="col-md-2">{% block main_r_content %}main_r_content{% endblock main_r_content %}</div>
    </div>
  {% endblock mainfullcontent %}
  </div>

  <!-- Footer NONE -->
{% endblock content %}

templates/main_lonly.html
{% extends '_base.html' %}

{% block content %}
  <!-- Menu NONE -->

  <!-- mainfull Content -->
  <div class="container-fluid">
  {% block mainfullcontent %}
    <div class="row text-center">
      <div class="col-md-3">{% block main_l_content %}main_l_content{% endblock main_l_content %}</div>
      <div class="col-md-9">{% block main_mid_content %}main_mid_content{% endblock main_mid_content %}</div>
    </div>
  {% endblock mainfullcontent %}
  </div>

  <!-- Footer NONE -->
{% endblock content %}

templates/main_menu.html
{% extends '_base.html' %}

{% block content %}
  <!-- Menu NONE -->

  <!-- mainfull Content -->
  <div class="container-fluid">
      {% block mainfullcontent %}
        <p>Default content...</p>
      {% endblock mainfullcontent %}
  </div>

  <!-- Footer NONE -->
{% endblock content %}

templates/main_ronly.html
{% extends '_base.html' %}

{% block content %}
  <!-- Menu NONE -->

  <!-- mainfull Content -->
  <div class="container-fluid">
  {% block mainfullcontent %}
    <div class="row text-center">
      <div class="col-md-9">{% block main_mid_content %}main_mid_content{% endblock main_mid_content %}</div>
      <div class="col-md-3">{% block main_r_content %}main_r_content{% endblock main_r_content %}</div>
    </div>
  {% endblock mainfullcontent %}
  </div>

  <!-- Footer NONE -->
{% endblock content %}

templates/middle.html
{% extends '_base.html' %}

{% block content %}
<!-- Menu NONE -->

<!-- Content -->
<div class="container-md justify-content-center">
	<div class="row justify-content-center">
		<div class="col-md-10">
			{% block middlecontent %}
			<p>Default content...</p>
			{% endblock middlecontent %}
		</div>
	</div>
</div>
<!-- Footer NONE -->
{% endblock content %}

templates/not-found.html
<h2>You are lost </h2>

<p>Here are some helpful links</p>

<ul>
    <li>
      <a href={% url 'home' %}>Go back home</a>  
        </li>
</ul>

templates/server-error.html
<h2>Something went wrong </h2>

<p>We track these issues automatically and our team is on it</p>

<ul>
    <li>
      <a href={% url 'home' %}>home</a>  
        </li>
</ul>