api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'), # localhost:8000/api/
    path('server_info/', views.index, name='server_info'),
    path('api_home/', views.api_home, name='api_home'), # localhost:8000/api/
    path('product_home_raw/', views.product_home_raw, name='product_home_raw'),
    # path('', views.index, name='index'),
    # path('', views.index, name='index'),



    # path('auth/', obtain_auth_token),
    # path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    # # path('products/', include('products.urls'))
]

django-ulti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),

    path("", include("core.urls")),
    path('blog/', include('blog.urls')),
    path('social/', include('social.urls')),
    path('todo/', include('todo.urls')),
    path('music/', include('music.urls')),
    path('radio/', include('radio.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

handler404 = 'django-ulti.views.custom_error_404'
handler500 = 'django-ulti.views.custom_error_500'
handler403 = 'django-ulti.views.custom_error_403'

homeserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),

    path("", include("core.urls")),
    path('blog/', include('blog.urls')),
    path('social/', include('social.urls')),
    path('todo/', include('todo.urls')),
    path('music/', include('music.urls')),
    path('radio/', include('radio.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

handler404 = 'homeserver.views.custom_error_404'
handler500 = 'homeserver.views.custom_error_500'
handler403 = 'homeserver.views.custom_error_403'

social/urls.py
from django.urls import path

from . import views


app_name = 'social'

urlpatterns = [
    # path("", index.as_view(), name="home"),
    path('', views.index, name='index'),
    path('settings/', views.settings, name='settings'),
    path('upload', views.upload, name='upload'),
    path('follow', views.follow, name='follow'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('like-post/', views.like_post, name='like-post'),
    path('logout/', views.logout, name='logout'),
    # path('signin/', views.signin, name='signin'),


    path('search/', views.search, name='search'),
    # path('signup/', views.signup, name='signup'),
]

social/models.py
from django.db import models
from django.contrib.auth import get_user_model
import uuid
from datetime import datetime
from core.models import TrackingModel

User = get_user_model()

# Create your models here.
class SocialProfile(TrackingModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_user = models.IntegerField()
    profile_bio = models.TextField(blank=True)
    profile_img = models.ImageField(upload_to='profile_images', default='blank-profile-picture.png')
    # location = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.username

class Post(TrackingModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.CharField(max_length=100)
    image = models.ImageField(upload_to='post_images')
    caption = models.TextField()
    # created_at = models.DateTimeField(default=datetime.now)
    no_of_likes = models.IntegerField(default=0)
    no_of_dislikes = models.IntegerField(default=0)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user

class Comment(TrackingModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.CharField(max_length=100)
    # image = models.ImageField(upload_to='post_images')
    comment = models.TextField(max_length=1024)
    no_of_likes = models.IntegerField(default=0)
    no_of_dislikes = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post")
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user

class LikePost(models.Model):
    post_id = models.CharField(max_length=500)
    username = models.CharField(max_length=100)

    def __str__(self):
        return self.username

class FollowersCount(models.Model):
    follower = models.CharField(max_length=100)
    user = models.CharField(max_length=100)

    def __str__(self):
        return self.user

social/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth
from django.contrib import messages
# messages.add_message(request, messages.SUCCESS, "{}".format('Message!'))
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import SocialProfile, Post, LikePost, FollowersCount
#from .models import Post, LikePost, FollowersCount
from itertools import chain
import random
from core.models import User

# Create your views here.

@login_required(login_url='account_login')
def index(request):
    user_object = User.objects.get(username=request.user.username)
    try:
        user_profile = SocialProfile.objects.get(user=user_object)
    except:
        #create a SocialProfile object for the new user
        messages.add_message(request, messages.SUCCESS, "{}".format('Social Profile Created!'))
        user_model = User.objects.get(username=request.user.username)
        new_profile = SocialProfile.objects.create(user=user_model, id_user=user_model.id)
        new_profile.save()
        return redirect('social:settings')

    user_following_list = []
    feed = []

    user_following = FollowersCount.objects.filter(follower=request.user.username)

    for users in user_following:
        user_following_list.append(users.user)

    for usernames in user_following_list:
        feed_lists = Post.objects.filter(user=usernames)
        feed.append(feed_lists)

    feed_list = list(chain(*feed))

    # user suggestion starts
    all_users = User.objects.all()
    user_following_all = []

    for user in user_following:
        user_list = User.objects.get(username=user.user)
        user_following_all.append(user_list)

    new_suggestions_list = [x for x in list(all_users) if (x not in list(user_following_all))]
    current_user = User.objects.filter(username=request.user.username)
    final_suggestions_list = [x for x in list(new_suggestions_list) if ( x not in list(current_user))]
    random.shuffle(final_suggestions_list)

    username_profile = []
    username_profile_list = []

    for users in final_suggestions_list:
        username_profile.append(users.id)

    for ids in username_profile:
        profile_lists = SocialProfile.objects.filter(id_user=ids)
        username_profile_list.append(profile_lists)

    suggestions_username_profile_list = list(chain(*username_profile_list))


    return render(request, 'social/index.html', {'user_profile': user_profile, 'posts':feed_list, 'suggestions_username_profile_list': suggestions_username_profile_list[:4]})

@login_required(login_url='account_login')
def upload(request):

    if request.method == 'POST':
        user = request.user.username
        image = request.FILES.get('image_upload')
        caption = request.POST['caption']

        new_post = Post.objects.create(user=user, image=image, caption=caption)
        new_post.save()

        return redirect('/social/')
    else:
        return redirect('/social/')

@login_required(login_url='account_login')
def search(request):
    user_object = User.objects.get(username=request.user.username)
    user_profile = SocialProfile.objects.get(user=user_object)

    if request.method == 'POST':
        username = request.POST['username']
        username_object = User.objects.filter(username__icontains=username)

        username_profile = []
        username_profile_list = []

        for users in username_object:
            username_profile.append(users.id)

        for ids in username_profile:
            profile_lists = SocialProfile.objects.filter(id_user=ids)
            username_profile_list.append(profile_lists)

        username_profile_list = list(chain(*username_profile_list))
    return render(request, 'social/search.html', {'user_profile': user_profile, 'username_profile_list': username_profile_list})

@login_required(login_url='account_login')
def like_post(request):
    username = request.user.username
    post_id = request.GET.get('post_id')

    post = Post.objects.get(id=post_id)

    like_filter = LikePost.objects.filter(post_id=post_id, username=username).first()

    if like_filter == None:
        new_like = LikePost.objects.create(post_id=post_id, username=username)
        new_like.save()
        post.no_of_likes = post.no_of_likes+1
        post.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'), '/social/')
    else:
        like_filter.delete()
        post.no_of_likes = post.no_of_likes-1
        post.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'), '/social/')

@login_required(login_url='account_login')
def profile(request, pk):
    user_object = User.objects.get(username=pk)
    user_profile = SocialProfile.objects.get(user=user_object)
    user_posts = Post.objects.filter(user=pk)
    user_post_length = len(user_posts)

    follower = request.user.username
    user = pk

    if FollowersCount.objects.filter(follower=follower, user=user).first():
        button_text = 'Unfollow'
    else:
        button_text = 'Follow'

    user_followers = len(FollowersCount.objects.filter(user=pk))
    user_following = len(FollowersCount.objects.filter(follower=pk))

    context = {
        'user_object': user_object,
        'user_profile': user_profile,
        'user_posts': user_posts,
        'user_post_length': user_post_length,
        'button_text': button_text,
        'user_followers': user_followers,
        'user_following': user_following,
    }
    return render(request, 'social/profile.html', context)

@login_required(login_url='account_login')
def follow(request):
    if request.method == 'POST':
        follower = request.POST['follower']
        user = request.POST['user']

        if FollowersCount.objects.filter(follower=follower, user=user).first():
            delete_follower = FollowersCount.objects.get(follower=follower, user=user)
            delete_follower.delete()
            return redirect('/social/profile/'+user)
        else:
            new_follower = FollowersCount.objects.create(follower=follower, user=user)
            new_follower.save()
            return redirect('/social/profile/'+user)
    else:
        return redirect('/social/')

@login_required(login_url='account_login')
def settings(request):
    user_profile = SocialProfile.objects.get(user=request.user)

    if request.method == 'POST':

        if request.FILES.get('image') == None:
            image = user_profile.profile_img
            bio = request.POST['bio']
            location = request.POST['location']

            user_profile.profile_img = image
            user_profile.profile_bio = bio
            user_profile.location = location
            user_profile.save()
        if request.FILES.get('image') != None:
            image = request.FILES.get('image')
            bio = request.POST['bio']
            location = request.POST['location']

            user_profile.profile_img = image
            user_profile.profile_bio = bio
            user_profile.location = location
            user_profile.save()

        return redirect('social:settings')
    return render(request, 'social/setting.html', {'user_profile': user_profile})

# def signup(request):
#
#     if request.method == 'POST':
#         username = request.POST['username']
#         email = request.POST['email']
#         password = request.POST['password']
#         password2 = request.POST['password2']
#
#         if password == password2:
#             if User.objects.filter(email=email).exists():
#                 messages.info(request, 'Email Taken')
#                 return redirect('signup')
#             elif User.objects.filter(username=username).exists():
#                 messages.info(request, 'Username Taken')
#                 return redirect('signup')
#             else:
#                 user = User.objects.create_user(username=username, email=email, password=password)
#                 user.save()
#
#                 #log user in and redirect to settings page
#                 user_login = auth.authenticate(username=username, password=password)
#                 auth.login(request, user_login)
#
#                 #create a SocialProfile object for the new user
#                 user_model = User.objects.get(username=username)
#                 new_profile = SocialProfile.objects.create(user=user_model, id_user=user_model.id)
#                 new_profile.save()
#                 return redirect('social:settings')
#         else:
#             messages.info(request, 'Password Not Matching')
#             return redirect('social:signup')
#
#     else:
#         return render(request, 'social/signup.html')
#
# def signin(request):
#
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#
#         user = auth.authenticate(username=username, password=password)
#
#         if user is not None:
#             auth.login(request, user)
#             return redirect('/social/')
#         else:
#             messages.info(request, 'Credentials Invalid')
#             return redirect('account_login')
#
#     else:
#         return render(request, 'social/index.html')

@login_required(login_url='account_login')
def logout(request):
    auth.logout(request)
    return redirect('core:home')

social/templates/social/profile.html
{% extends 'middle.html' %}
{% load static %}
{% block title %}Social - Profile{% endblock title %}

{% block style %}
<!-- <link rel="stylesheet" href="{% static 'social/assets/css/icons.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'social/assets/css/uikit.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'social/assets/css/style.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'social/assets/css/tailwind.css' %}"> -->

<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
{% endblock style %}

{% block mainnavsocialactive %}active{% endblock mainnavsocialactive %}

{% block submenu %}
{% endblock submenu %}

{% block breadcrumb %}
<!-- Breadcrumb -->
<div class="container-fluid px-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'social:index' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Account Setting for <b>{{user.username}}</b></li>
    </ol>
  </nav>
</div>

{% endblock breadcrumb %}

{% block middlecontent %}
<div class="container-fluid">
<div class="row">
  <div class="col text-center">
    <div class="position-relative">
      <img src="{% static 'social/images/resources/timeline-1.jpg' %}" class=" h-auto w-100 mx-auto px-0 rounded-5 img-fluid" style="max-height: 10rem; max-width: 1199px;" alt="...">
      <div class="position-absolute top-50 start-50 translate-middle">
        <h3 class="text-light">
          @{{user_profile.user.username}}
        </h5>
        <form action="/social/follow" method="POST">
          {% csrf_token %}
          <input type="hidden" value="{{user.username}}" name="follower" />
          <input type="hidden" value="{{user_object.username}}" name="user" />

          {% if user_object.username == user.username %}
          <!-- <a class="btn btn-primary" href="{% url 'social:settings'%}" role="button">Account Settings</a> -->
          {% else %}
          <button class="btn btn-primary" type="submit">{{button_text}}</button>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
</div>


<div class="row">

<div class="col-md-8">
  {% for post in user_posts %}


  <div class="card mt-3 mx-3">
    <div class="card-header text-end">
      <div class='row mt-1 mb-0'>


        <div class='col-md-10  text-start'>
          Posted by <a href="/social/profile/{{post.user}}">@{{post.user}}</a>
        </div>

        <div class='col-md-2 text-end'>
          <div class="dropdown">
            <button class="btn btn-primary btn-sm dropdown-toggle mx-0 px-1 pt-1 pb-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-three-dots"></i>
            </button>
            <ul class="dropdown-menu">
              <li>
                <a href="{{post.image.url}}" class="dropdown-item flex" download>
                  <i class="bi bi-cloud-download"></i>
                  &nbsp;Download
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="bi bi-trash"></i>
                  &nbsp;Delete Post (NEED FIX)
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="bi bi-trash"></i>
                  &nbsp;Ban User (NEED FIX)
                </a>
              </li>
            </ul>
          </div>
        </div>


      </div>


    </div>

    <div class="row g-0">
      <div class="col-md-4">

        <a href="#" data-bs-toggle="modal" data-bs-target="#imageModal{{post.id}}" data-bs-whatever=""><img src="{{post.image.url}}" style="height: 190px; max-width:190px" class="img-fluid p-3" alt=""></a>

        <div class="modal fade" id="imageModal{{post.id}}" tabindex="-1" aria-labelledby="imageModalLabel{{post.id}}" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-fullscreen-md-down w-25">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="imageModalLabel{{post.id}}"></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <img src="{{post.image.url}}" class="w-100" stylealt="">
              </div>
              <div class="modal-footer text-muted">
                Posted: {{post.created_at}}
              </div>
            </div>
          </div>
        </div>


      <!-- Vertically centered modal -->
      <div class="modal-dialog modal-dialog-centered">

      </div>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"></h5>
          <p class="card-text text-center">
            {{post.caption}}
          </p>
          <p class="card-text text-end">
            <small class="text-muted">Posted: {{post.created_at}}</small>
          </p>
        </div>
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">comment #1</li>
      <li class="list-group-item">comment #1</li>
      <li class="list-group-item">comment #1</li>
    </ul>
    <div class="card-footer text-muted">
      <div class="row">
        <div class="col text-start">
          Add comment area (NEED)
        </div>

        <div class="col text-end">
          <button type="button" class="btn btn-primary btn-sm text-light">
            <a href="/social/like-post?post_id={{post.id}}" class="text-light">
                <i class="bi bi-hand-thumbs-up-fill"></i>
                {% if post.no_of_likes == 0 %}
                No likes
                {% elif post.no_of_likes == 1 %}
                Liked by {{post.no_of_likes}} person
                {% else %}
                Liked by {{post.no_of_likes}} people
                {% endif %}
            </a>
          </button>


        </div>
      </div>





    </div>
  </div>
  {% endfor %}
</div>

<div class="col-md-4">
  <div class="card text-center mt-3 mx-3">
    <div class="card-header position-relative">

      <a class="" href="{% url 'social:profile' user %}">
        <img src="{{user_profile.profile_img.url}}" style="height: 190px; max-width:190px" class="rounded-circle w-auto position-absolute top-0 start-50 translate-middle" alt="">
      </a>

      <div class="btn-group mt-5">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#uploadPicModal">
          <i class="bi bi-cloud-upload-fill"></i> Upload Pics
        </button>

        <!-- Modal -->
        <div class="modal fade" id="uploadPicModal" tabindex="-1" aria-labelledby="uploadPicModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="uploadPicModalLabel">Upload Pics</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-center">

                <form action="upload" method="POST" enctype="multipart/form-data" >
                {% csrf_token %}

                <div>
                    <input type="file" name="image_upload">
                    <!-- <a href="#" class="button soft-warning small"> Choose file</a> -->
                    <textarea class="button soft-warning small" name="caption" placeholder="caption..." ></textarea>
                    <div class="py-2 text-sm">
                        Your Image size Must be Maxmium 999MB
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                      <button class="btn btn-primary" type="submit">Upload</button>
                    </div>
                </div>
                </form>

              </div>
            </div>
          </div>
        </div>

        <button type="button" class="btn btn-sm btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
          <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'social:profile' user %}">Profile</a></li>
          <li><a class="dropdown-item" href="{% url 'social:settings' %}">Account setting</a></li>
          <li><a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a></li>
        </ul>
      </div>
    </div>

    <div class="card-body my-0 pt-2 pb-0">
      <h5 class="card-title">Bio</h5>
      <p class="card-text">
        {{user_profile.profile_bio}}
      </p>
    </div>


    <div class="card-body my-0 pt-2 pb-0">
      <!-- <h5 class="card-title">Card title           sdfasdfasdfasdfasdf</h5> -->
      <p class="card-text">
        <form  class="d-flex" role="search" action="/social/search/" name="username" method="POST">
          {% csrf_token %}
          <input  class="form-control me-2" type="search" name="username" placeholder="Search for username.." aria-label="Search">
          <button class="btn btn-primary" type="submit">Search</button>
        </form>
      </p>
    </div>

    <div class="card-footer text-muted">

        {% if user_post_length == 0 %}
        No Post
        {% elif user_post_length == 1 %}
        {{user_post_length}} Post
        {% else %}
        {{user_post_length}} Posts
        {% endif %}

        --

        {% if user_followers == 0 or user_followers == 1 %}
        {{user_followers}} follower
        {% else %}
        {{user_followers}} followers
        {% endif %}

        --

        {{user_following}} following

    </div>

  </div>

</div>
</div>
</div>




{% endblock middlecontent %}

{% block javascript_custom %}
<script>
  const imageModal = document.getElementById('imageModal')
  imageModal.addEventListener('show.bs.modal', event => {
    // Button that triggered the modal
    const button = event.relatedTarget
    // Extract info from data-bs-* attributes
    const recipient = button.getAttribute('data-bs-whatever')
    // If necessary, you could initiate an AJAX request here
    // and then do the updating in a callback.
    //
    // Update the modal's content.
    const modalTitle = imageModal.querySelector('.modal-title')
    const modalBodyInput = imageModal.querySelector('.modal-body input')

    modalTitle.textContent = `New message to ${recipient}`
    modalBodyInput.value = recipient
  })
</script>
<!-- <script src="{% static 'social/assets/js/tippy.all.min.js' %}"></script> -->
<!-- <script src="{% static 'social/assets/js/jquery-3.3.1.min.js' %}"></script> -->
<!-- <script src="{% static 'social/assets/js/uikit.js' %}"></script> -->
<!-- <script src="{% static 'social/assets/js/simplebar.js' %}"></script> -->
<!-- <script src="{% static 'social/assets/js/custom.js' %}"></script> -->

<!-- <script src="{% static 'social/../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script> -->
{% endblock javascript_custom %}

social/templates/social/search.html
{% extends 'middle.html' %}
{% load static %}
{% block title %}Social - Search{% endblock title %}

{% block style %}
{% endblock style %}

{% block mainnavsocialactive %}active{% endblock mainnavsocialactive %}

{% block submenu %}
{% endblock submenu %}

{% block middlecontent %}
<h4>Results For <span class="fw-semi-bold"><b>{{username}}</b></span></h4>


{% for users in username_profile_list %}
<div class="card text-center">
<div class="card-header">
  <a href="/social/profile/{{users.user}}"><b>@{{users.user}}</b></a>
</div>
<div class="row g-0">
    <div class="col-md-2">
      <img src="{{ user_profile.profile_img.url }}" class="img-fluid" alt="...">
    </div>
    <div class="col-md-10">
      <div class="card-body">
        <h5 class="card-title">{{users.location}}</h5>
        <p class="card-text">{{users.bio}}</p>
      </div>
    </div>
  </div>


{% endfor %}
{% endblock middlecontent %}

{% block javascript_custom %}
{% endblock javascript_custom %}

social/templates/social/setting.html
{% extends 'middle.html' %}
{% load static %}
{% block title %}Social - Settings{% endblock title %}

{% block style %}
<!-- <link rel="stylesheet" href="{% static 'social/assets/css/icons.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'social/assets/css/uikit.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'social/assets/css/style.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'social/assets/css/tailwind.css' %}"> -->

<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
{% endblock style %}

{% block mainnavsocialactive %}active{% endblock mainnavsocialactive %}

{% block submenu %}
{% endblock submenu %}

{% block breadcrumb %}
<!-- Breadcrumb -->
<div class="container-fluid px-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'social:index' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Account Setting for <b>{{user.username}}</b></li>
    </ol>
  </nav>
</div>

{% endblock breadcrumb %}

{% block middlecontent %}

  <form action="" method="POST" enctype="multipart/form-data" class='mb-0'>
    {% csrf_token %}
    <div class="card mw-50">
      <div class="card-header">
        Profile Settings
      </div>
      <img style="height: 400px; max-width: 400px;" class="rounded-circle card-img-top h-auto w-100 mx-auto px-5" src="{{user_profile.profile_img.url}}"/>

      <div class="card-body">
        <h5 class="card-title">Bio</h5>
        <p class="card-text">{{user_profile.profile_bio}}</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <h5 class="card-title"> Profile Image</h5>
          <div class="mb-3">
            <input class="form-control" type="file" name="image">
          </div>
        </li>
        <li class="list-group-item">
          <h5 class="card-title"> Banner Image (Need FIX)</h5>
          <div class="mb-3">
            <input class="form-control" type="file" name="bannerimage">
          </div>
        </li>
        <li class="list-group-item">
          <h5 class="card-title">Update Bio</h5>
          <div class="form-floating">
            <textarea class="form-control" placeholder="{{user_profile.profile_bio}}" id="about" name="bio" style="height: 200px"></textarea>
            <label for="floatingTextarea" class="form-label text-muted fs-6 fw-light">Update new bio here..</label>
          </div>
        </li>
        <li class="list-group-item">
          <h5 class="card-title">Location</h5>
          <div class="form-floating">
            <input class="form-control" placeholder="{{user_profile.location}}" id="about" name="location"></textarea>
            <label for="floatingTextarea" class="form-label text-muted fs-6 fw-light">{{user_profile.location}}</label>
          </div>

        </li>
      </ul>

      <div class="card-footer text-end">
        <a class="btn btn-danger" href="#" role="button">Cancel</a>
        <button type="submit" class="btn btn-primary"> Save </button>
      </div>
    </div>
  </form>

{% endblock middlecontent %}

{% block javascript_custom %}
<!-- <script src="{% static 'social/assets/js/tippy.all.min.js' %}"></script> -->
<!-- <script src="{% static 'social/assets/js/jquery-3.3.1.min.js' %}"></script> -->
<!-- <script src="{% static 'social/assets/js/uikit.js' %}"></script> -->
<!-- <script src="{% static 'social/assets/js/simplebar.js' %}"></script> -->
<!-- <script src="{% static 'social/assets/js/custom.js' %}"></script> -->

<!-- <script src="{% static 'social/../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script> -->
{% endblock javascript_custom %}